// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:core';
import 'package:apiintegration/BO/AvengerBO/AvengerBO.dart' as prefix1;
import 'package:dart_json_mapper/src/model/annotations.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.JsonSerializable(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'AvengerBO',
            r'.AvengerBO',
            134217735,
            0,
            const prefix0.JsonSerializable(),
            const <int>[0, 1, 6],
            const <int>[7, 8, 9, 10, 11, 2, 3, 4, 5],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) => ({id, name}) =>
                  b ? prefix1.AvengerBO(id: id, name: name) : null
            },
            -1,
            0,
            const <int>[],
            const <Object>[prefix0.jsonSerializable],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(
            r'id',
            67239941,
            0,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1, const <int>[], const []),
        r.VariableMirrorImpl(
            r'name',
            67239941,
            0,
            const prefix0.JsonSerializable(),
            -1,
            2,
            2, const <int>[], const []),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 0, 2),
        r.ImplicitSetterMirrorImpl(const prefix0.JsonSerializable(), 0, 3),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 1, 4),
        r.ImplicitSetterMirrorImpl(const prefix0.JsonSerializable(), 1, 5),
        r.MethodMirrorImpl(r'', 0, 0, -1, 0, 0, const <int>[],
            const <int>[0, 1], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'==', 2097154, -1, -1, 3, 3, const <int>[],
            const <int>[4], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'toString', 2097154, -1, -1, 4, 4, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(
            r'noSuchMethod',
            524290,
            -1,
            -1,
            -1,
            -1,
            const <int>[],
            const <int>[5],
            const prefix0.JsonSerializable(),
            const []),
        r.MethodMirrorImpl(r'hashCode', 2097155, -1, -1, 5, 5, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'runtimeType', 2097155, -1, -1, 6, 6, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(
            r'id',
            67249158,
            6,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1,
            const <int>[],
            const [],
            null,
            #id),
        r.ParameterMirrorImpl(
            r'name',
            67249158,
            6,
            const prefix0.JsonSerializable(),
            -1,
            2,
            2,
            const <int>[],
            const [],
            null,
            #name),
        r.ParameterMirrorImpl(
            r'_id',
            67240038,
            3,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_name',
            67240038,
            5,
            const prefix0.JsonSerializable(),
            -1,
            2,
            2,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'other',
            134348806,
            7,
            const prefix0.JsonSerializable(),
            -1,
            7,
            7,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'invocation',
            134348806,
            9,
            const prefix0.JsonSerializable(),
            -1,
            8,
            8,
            const <int>[],
            const [],
            null,
            null)
      ],
      <Type>[
        prefix1.AvengerBO,
        int,
        String,
        bool,
        String,
        int,
        Type,
        Object,
        Invocation
      ],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'id': (dynamic instance) => instance.id,
        r'name': (dynamic instance) => instance.name
      },
      {
        r'id=': (dynamic instance, value) => instance.id = value,
        r'name=': (dynamic instance, value) => instance.name = value
      },
      null,
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
